### ISSUE TITLE
add "max.request.size" to KafkaConfiguration

### ISSUE THREAD

**Issue by christopher-johnson** [trellis-ldp/trellis-app#3]
The default `max.request.size` for [KafkaProducer](https://kafka.apache.org/documentation/#producerconfigs) is 1M.  I have encountered errors for messages that could not be delivered because the requests were too large (some are as large as 3M).  

Not clear why this happens (Kafka tuning is "kafkaesque"), but raising it to 5M has alleviated this issue for me.  Could this be added as a configuration option?

**Comment by acoburn** [comment]
Actually, you should be able to add _any_ kafka properties to the configuration like so:

```yaml
kafka:
    max.request.size: 5M
```

**Comment by acoburn** [comment]
There may also be a deeper issue here, related to what goes into the kafka messages. Presumably, it would be possible to filter out most of the data, since those messages _should_ be quite small.

**Comment by christopher-johnson** [comment]
OK. great.  Nice to know that any properties can be added.  I will do some analysis on the requests and see if I can reveal what is going on.  For reference, [this article](http://cloudurable.com/blog/kafka-tutorial-kafka-producer-advanced-java-examples/index.html) explains somewhat how advanced Producer configuration can work... rather involved.
